Repository rl-institut/E_Metrobus, pull requests merged in 2020-04, with the labels that each got.

#136 Departure station can be changed
  CHANGELOG.md
  e_metrobus/static/js/stations.js
Labels: enhancement

#140 Added real station data
  e_metrobus/navigation/stations.csv
  e_metrobus/navigation/stations.py
  e_metrobus/navigation/views.py
  e_metrobus/templates/navigation/display_route.html
Labels: enhancement

#142 Carousel
  CHANGELOG.md
  e_metrobus/static/images/icons/Icon_Conventional_Bus.svg
  e_metrobus/static/images/icons/Icon_Conventional_Car.svg
  e_metrobus/static/images/icons/Icon_Pedestrian_Bike.svg
  e_metrobus/static/images/icons/Icon_Pin.svg
  e_metrobus/static/images/icons/i_back_gray.svg
  e_metrobus/static/images/icons/i_next_black_large.svg
  e_metrobus/static/images/icons/i_next_gray.svg
  e_metrobus/static/images/icons/i_previous_black_large.svg
  e_metrobus/static/sass/_display_route.scss
  e_metrobus/templates/navigation/display_route.html
Labels: design

#149 Third station clears selection
  CHANGELOG.md
  e_metrobus/static/js/stations.js
Labels: enhancement

#134 Feedback page
  CHANGELOG.md
  e_metrobus/migrations/0002_feedback.py
  e_metrobus/migrations/0003_auto_20200403_1415.py
  e_metrobus/migrations/0004_auto_20200403_1416.py
  e_metrobus/navigation/forms.py
  e_metrobus/navigation/models.py
  e_metrobus/navigation/urls.py
  e_metrobus/navigation/views.py
  e_metrobus/navigation/widgets.py
  e_metrobus/static/images/icons/i_star_blue.svg
  e_metrobus/static/images/icons/i_star_gray.svg
  e_metrobus/static/js/feedback.js
  e_metrobus/static/sass/_feedback.scss
  e_metrobus/static/sass/app.scss
  e_metrobus/templates/navigation/feedback.html
  e_metrobus/templates/navigation/quiz_finished.html
  e_metrobus/templates/widgets/feedback_comment.html
  e_metrobus/templates/widgets/feedback_stars.html
Labels: enhancement

#141 Data infos
  e_metrobus/navigation/chart.py
  e_metrobus/navigation/constants.py
  e_metrobus/navigation/stations.py
  e_metrobus/navigation/views.py
  e_metrobus/navigation/widgets.py
  e_metrobus/static/sass/_comparison.scss
  e_metrobus/static/sass/_legal.scss
  e_metrobus/static/sass/_variables.scss
  e_metrobus/static/sass/app.scss
  e_metrobus/templates/navigation/comparison.html
  e_metrobus/templates/navigation/legal.html
  e_metrobus/templates/widgets/info_table.html
Labels: enhancement

#163 remove black bg-color from close button
  e_metrobus/static/sass/_comparison.scss
Labels: bug, design

#164 fix hidden stations bug
  e_metrobus/static/sass/_route.scss
Labels: bug, design
