Repository rl-institut/E_Metrobus, pull requests merged in 2020-03, with the labels that each got.

#100 Fe/new icons
  CHANGELOG.md
  e_metrobus/navigation/chart.py
  e_metrobus/static/images/icons/i_trophy_1_black.svg
  e_metrobus/static/images/icons/i_trophy_1_gray.svg
  e_metrobus/static/images/icons/i_trophy_2_black.svg
  e_metrobus/static/images/icons/i_trophy_2_gray.svg
  e_metrobus/static/images/icons/i_trophy_3_black.svg
  e_metrobus/static/images/icons/i_trophy_3_gray.svg
Labels: design

#97 Added QR-Code to desktop-page
  e_metrobus/static/images/qr-code.svg
  e_metrobus/static/sass/_landing_page.scss
  e_metrobus/templates/includes/desktop.html
Labels: design, enhancement

#67 Score can be saved and shared via link
  e_metrobus/navigation/views.py
  e_metrobus/templates/navigation/quiz_finished.html
Labels: design, enhancement

#105 Removed answer button on question page
  e_metrobus/templates/navigation/question.html
Labels: design, enhancement

#111 Added y-Axis label to chart
  e_metrobus/navigation/chart.py
Labels: design

#123 Reduce logos
  e_metrobus/static/sass/_landing_page.scss
  e_metrobus/templates/navigation/landing_page.html
Labels: design

#124 Reduce flag
  e_metrobus/static/images/qr-code.svg
  e_metrobus/static/sass/_landing_page.scss
  e_metrobus/static/sass/_top-bar.scss
Labels: design

#125 add new icons for dashboard, top-bar and comparison chart
  e_metrobus/navigation/questions.cfg
  e_metrobus/navigation/questions.py
  e_metrobus/navigation/views.py
  e_metrobus/static/images/icons/Icon_E_Bus_Front.svg
  e_metrobus/static/images/icons/i_e_bus_black.svg
  e_metrobus/static/images/icons/i_earth_black_fill.svg
  e_metrobus/static/images/icons/i_earth_black_line.svg
  e_metrobus/static/images/icons/i_ebus_black_fill.svg
  e_metrobus/static/images/icons/i_ebus_black_line.svg
  e_metrobus/static/images/icons/i_government_black_fill.svg
  e_metrobus/static/images/icons/i_government_black_line.svg
  e_metrobus/static/images/icons/i_human_black_fill.svg
  e_metrobus/static/images/icons/i_human_black_line.svg
  e_metrobus/static/images/icons/i_person_black.svg
Labels: design

#126 Landing page
  e_metrobus/static/images/Emetrobus_LP_img.png
  e_metrobus/static/images/icons/i_bus_black_line.svg
  e_metrobus/static/images/icons/i_bus_blue_line.svg
  e_metrobus/static/images/icons/i_electricity_black_line.svg
  e_metrobus/static/images/icons/i_electricity_blue_line.svg
  e_metrobus/static/images/icons/i_government_black_desktop.svg
  e_metrobus/static/images/icons/i_government_blue_desktop.svg
  e_metrobus/static/images/icons/i_time_black_line.svg
  e_metrobus/static/images/icons/i_time_blue_line.svg
  e_metrobus/static/sass/_landing_page.scss
  e_metrobus/static/sass/_settings.scss
  e_metrobus/templates/includes/desktop.html
Labels: enhancement
