Repository rl-institut/E_Metrobus, pull requests merged in 2020-05, with the labels that each got.

#166 add switch language btn to desktop page
  e_metrobus/static/sass/_landing_page.scss
  e_metrobus/templates/includes/desktop.html
Labels: enhancement

#159 First question answered after display_route
  CHANGELOG.md
  e_metrobus/navigation/questions.cfg
  e_metrobus/navigation/views.py
Labels: enhancement

#174 changed confetti color and updated wording
  e_metrobus/static/js/confetti.js
  e_metrobus/templates/navigation/quiz_finished.html
Labels: design

#175 changed top-nav star color to blue
  e_metrobus/templates/widgets/top_bar.html
Labels: design

#173 Feature/dashboard design
  e_metrobus/static/images/Dashboard_Pattern.svg
  e_metrobus/static/sass/_dashboard.scss
  e_metrobus/templates/navigation/dashboard.html
Labels: design

#176 Feature/lp animation
  e_metrobus/static/images/icons/Icon_Conventional_Bus.svg
  e_metrobus/static/images/icons/Icon_Conventional_Car.svg
  e_metrobus/static/images/icons/Icon_Route.svg
  e_metrobus/static/sass/_comparison.scss
  e_metrobus/static/sass/_display_route.scss
  e_metrobus/static/sass/_landing_page.scss
  e_metrobus/templates/navigation/comparison.html
  e_metrobus/templates/navigation/display_route.html
  e_metrobus/templates/navigation/landing_page.html
Labels: design

#178 add pattern bg to finished category page
  e_metrobus/static/images/Dashboard_Pattern_blue.svg
  e_metrobus/static/sass/_category_finished.scss
  e_metrobus/templates/navigation/category_finished.html
Labels: design

#188 move skip btn to top
  e_metrobus/static/sass/_feedback.scss
  e_metrobus/templates/navigation/feedback.html
Labels: design

#202 Lp screenshot
  e_metrobus/static/images/Dashboard_Pattern.svg
  e_metrobus/static/images/Dashboard_Pattern_blue.svg
  e_metrobus/static/images/LP_Device_v2.png
  e_metrobus/templates/includes/desktop.html
Labels: design

#216 reduce category_finished icons height
  e_metrobus/static/sass/_category_finished.scss
Labels: bug, design

#215 center skip btn
  e_metrobus/static/sass/_feedback.scss
Labels: design

#239 Feature/remove nav
  e_metrobus/static/sass/_layout.scss
  e_metrobus/templates/navigation/comparison.html
  e_metrobus/templates/navigation/display_route.html
Labels: design, enhancement

#240 update route image
  e_metrobus/static/images/Route_top_img_v2.svg
  e_metrobus/static/sass/_route.scss
Labels: design, enhancement

#236 Feature/sub
  e_metrobus/navigation/chart.py
  e_metrobus/navigation/questions.cfg
  e_metrobus/navigation/questions.py
  e_metrobus/templates/navigation/display_route.html
  e_metrobus/templates/navigation/environment.html
  e_metrobus/templates/pages/question_translations.html
  e_metrobus/templates/questions/environment/co2_reduction.html
  e_metrobus/templates/widgets/info_table.html
Labels: design, enhancement

#237 Fix/content height
  e_metrobus/static/sass/_animate_answer.scss
  e_metrobus/static/sass/_category_finished.scss
  e_metrobus/static/sass/_question.scss
Labels: design

#217 reduce back to route link width
  e_metrobus/static/sass/_top-bar.scss
  e_metrobus/templates/widgets/top_bar_route.html
Labels: design, enhancement

#241 add fb icon
  e_metrobus/static/images/icons/i_fb.png
  e_metrobus/templates/navigation/quiz_finished.html
Labels: design

#234 add higher z-index to share icons
  e_metrobus/static/sass/_quiz_finished.scss
Labels: bug

#245 add transparent bc-color to see data btn
  e_metrobus/static/sass/_comparison.scss
Labels: design
