Repository rl-institut/E_Metrobus, pull requests merged in 2020-06, with the labels that each got.

#253 Fix/footer
  e_metrobus/static/sass/_footer.scss
Labels: bug, design

#256 shorten LP animation time
  e_metrobus/static/sass/_landing_page.scss
Labels: design

#252 Design/icons
  e_metrobus/static/images/icons/i_info_black.svg
  e_metrobus/static/images/icons/i_info_gray.svg
  e_metrobus/static/images/icons/i_leaf_black.svg
  e_metrobus/static/images/icons/i_leaf_gray.svg
  e_metrobus/static/images/icons/i_quiz_black.svg
  e_metrobus/static/images/icons/i_quiz_gray.svg
  e_metrobus/static/images/icons/i_results_black.svg
Labels: design

#242 add favicon
  CHANGELOG.md
  e_metrobus/static/favicon/android-chrome-192x192.png
  e_metrobus/static/favicon/android-chrome-512x512.png
  e_metrobus/static/favicon/apple-touch-icon.png
  e_metrobus/static/favicon/browserconfig.xml
  e_metrobus/static/favicon/favicon-16x16.png
  e_metrobus/static/favicon/favicon-32x32.png
  e_metrobus/static/favicon/favicon.ico
  e_metrobus/static/favicon/mstile-144x144.png
  e_metrobus/static/favicon/mstile-150x150.png
  e_metrobus/static/favicon/mstile-310x150.png
  e_metrobus/static/favicon/mstile-310x310.png
  e_metrobus/static/favicon/mstile-70x70.png
  e_metrobus/static/favicon/safari-pinned-tab.svg
  e_metrobus/static/favicon/site.webmanifest
  e_metrobus/templates/base.html
Labels: design, enhancement

#268 add links to logos on mobile LP
  e_metrobus/templates/navigation/landing_page.html
Labels: enhancement

#270 increase distance km font-size
  e_metrobus/templates/navigation/display_route.html
Labels: design

#272 Redesign progress circle
  CHANGELOG.md
  e_metrobus/navigation/constants.py
  e_metrobus/navigation/questions.py
  e_metrobus/navigation/views.py
  e_metrobus/static/sass/_question.scss
  e_metrobus/templates/navigation/dashboard.html
  e_metrobus/templates/navigation/question.html
Labels: design, enhancement

#275 fix jumping page on display_route and comparison
  e_metrobus/static/sass/_layout.scss
Labels: bug, design

#279 Feature/bug feedback
  CHANGELOG.md
  config/settings/base.py
  e_metrobus/migrations/0005_bug.py
  e_metrobus/migrations/0006_auto_20200611_1045.py
  e_metrobus/navigation/forms.py
  e_metrobus/navigation/models.py
  e_metrobus/navigation/urls.py
  e_metrobus/navigation/views.py
  e_metrobus/static/sass/_feedback.scss
  e_metrobus/templates/navigation/bug.html
  e_metrobus/templates/navigation/legal.html
Labels: design, enhancement

#286 increase station names font sizes
  e_metrobus/static/sass/_display_route.scss
Labels: design

#288 Feature/footer new order
  CHANGELOG.md
  e_metrobus/navigation/widgets.py
  e_metrobus/static/images/icons/i_flash_black.svg
  e_metrobus/static/images/icons/i_flash_gray.svg
  e_metrobus/static/images/icons/i_pin_black.svg
  e_metrobus/static/images/icons/i_pin_gray.svg
  e_metrobus/static/sass/_footer.scss
  e_metrobus/templates/widgets/footer.html
Labels: design

#290 Feature/footer style
  e_metrobus/static/images/icons/i_flash_gray.svg
  e_metrobus/static/images/icons/i_info_gray.svg
  e_metrobus/static/images/icons/i_pin_gray.svg
  e_metrobus/static/images/icons/i_quiz_gray.svg
  e_metrobus/static/sass/_footer.scss
Labels: design

#295 align legal tabs correctly
  e_metrobus/static/sass/_components.scss
Labels: design

#294 Feature/animations
  e_metrobus/static/sass/_display_route.scss
  e_metrobus/templates/navigation/display_route.html
Labels: design, enhancement

#291 Feature/single page tour
  CHANGELOG.md
  e_metrobus/navigation/urls.py
  e_metrobus/navigation/views.py
  e_metrobus/static/images/Dashboard_Pattern_blue_v2.svg
  e_metrobus/static/images/Icon_E_Bus_BVG_error.svg
  e_metrobus/static/images/LP_Device_v2.png
  e_metrobus/static/images/Route_top_img_v2.svg
  e_metrobus/static/sass/_tour.scss
  e_metrobus/static/sass/app.scss
  e_metrobus/templates/navigation/comparison.html
  e_metrobus/templates/navigation/dashboard.html
  e_metrobus/templates/navigation/tour.html
Labels: design, enhancement

#297 Feature/privacy policy
  CHANGELOG.md
  e_metrobus/navigation/urls.py
  e_metrobus/navigation/views.py
  e_metrobus/static/sass/_components.scss
  e_metrobus/static/sass/_landing_page.scss
  e_metrobus/templates/navigation/landing_page.html
Labels: enhancement

#307 Feature/logo lp
  e_metrobus/static/images/logos/Logokombi_gefoerdert-durch-BMVI-koordiniert-durch-NOW_de.png
  e_metrobus/static/sass/_landing_page.scss
  e_metrobus/templates/includes/desktop.html
  e_metrobus/templates/navigation/landing_page.html
Labels: design, enhancement

#310 Feature/new single page tour
  e_metrobus/static/sass/_tour.scss
  e_metrobus/static/sass/_variables.scss
  e_metrobus/templates/navigation/tour.html
Labels: design

#309 Feature/dashboard flash
  CHANGELOG.md
  e_metrobus/navigation/questions.py
  e_metrobus/navigation/views.py
  e_metrobus/static/images/icons/i_ebus_black_line.svg
  e_metrobus/static/images/icons/i_flash_correct.svg
  e_metrobus/static/images/icons/i_flash_empty.svg
  e_metrobus/static/images/icons/i_flash_wrong.svg
  e_metrobus/static/sass/_dashboard.scss
  e_metrobus/templates/navigation/dashboard.html
Labels: design, enhancement

#315 Feature/new answer page
  CHANGELOG.md
  e_metrobus/navigation/urls.py
  e_metrobus/navigation/views.py
  e_metrobus/static/images/icons/i_flash_white.svg
  e_metrobus/static/sass/_question.scss
  e_metrobus/static/sass/_variables.scss
  e_metrobus/templates/navigation/answer.html
  e_metrobus/templates/navigation/answer_score.html
  e_metrobus/templates/navigation/question.html
Labels: design

#326 add accordion with dummy pictures to summary page
  CHANGELOG.md
  e_metrobus/static/sass/_questions_as_text.scss
  e_metrobus/templates/navigation/questions_as_text.html
Labels: bug, design, enhancement

#324 style and animate categorry_finished page
  e_metrobus/static/sass/_category_finished.scss
  e_metrobus/templates/navigation/category_finished.html
Labels: design
